from __future__ import annotations

import logging

from fastapi import APIRouter, HTTPException, Request, Response

from review_app.forms import validate_and_prepare_form
from review_app.pdf_builder import build_pdf
from domain.export import validate_official_export

logger = logging.getLogger("review.pdf")
router = APIRouter(tags=["pdf"])

@router.post("/api/pdf")
async def api_pdf(request: Request):
    try:
        payload = await request.json()
    except Exception as e:
        raise HTTPException(status_code=400, detail="Invalid JSON") from e
    if not isinstance(payload, dict):
        raise HTTPException(status_code=400, detail="Invalid JSON")

    draft = str(request.query_params.get("draft", "")).strip().lower() in {
        "1",
        "true",
        "yes",
        "on",
    }
    form_obj = payload.get("form") if isinstance(payload.get("form"), dict) else payload

    if not draft:
        check = validate_official_export(form_obj)
        if not check["ok"]:
            raise HTTPException(
                status_code=400,
                detail={
                    "reason": "official_incomplete",
                    "message": check["message"],
                    "missing_count": check["missing_count"],
                    "missing": check["missing"][:40],
                    "hint": "Doplň hodnocení oficiálních otázek, nebo stáhni koncept PDF (?draft=1).",
                },
            )

    try:
        logger.info("[pdf] request received draft=%s", draft)
        pdf_bytes = build_pdf(form_obj)
        repo = None
        for s in form_obj.get("sections") or []:
            if isinstance(s, dict) and isinstance(s.get("meta"), dict) and s["meta"].get("repo"):
                repo = s["meta"]["repo"]
                break
        if not repo and isinstance(form_obj.get("meta"), dict):
            repo = form_obj["meta"].get("repo")
        base = (repo or "review").replace("/", "_")
        suffix = "_draft" if draft else ""
        headers = {"Content-Disposition": f"attachment; filename=form_{base}{suffix}.pdf"}
        logger.info("[pdf] generated bytes: %s, filename base: %s", len(pdf_bytes), base)
        return Response(content=pdf_bytes, media_type="application/pdf", headers=headers)
    except HTTPException:
        raise
    except Exception as e:
        logger.exception("[pdf] generation failed: %s", e)
        raise HTTPException(status_code=500, detail=f"Failed to generate PDF: {e}") from e

