/** Shared DOM refs and app state. */
export const dom = {
    navHomeBtn: document.getElementById('navHomeBtn'),
    navWorkBtn: document.getElementById('navWorkBtn'),
    navUsersBtn: document.getElementById('navUsersBtn'),
    viewHome: document.getElementById('viewHome'),
    viewWork: document.getElementById('viewWork'),
    viewUsers: document.getElementById('viewUsers'),
    authRoleBadge: document.getElementById('authRoleBadge'),
    authLoginForm: document.getElementById('authLoginForm'),
    authTabCode: document.getElementById('authTabCode'),
    authTabUser: document.getElementById('authTabUser'),
    loginUsername: document.getElementById('loginUsername'),
    loginPassword: document.getElementById('loginPassword'),
    createUserForm: document.getElementById('createUserForm'),
    usersList: document.getElementById('usersList'),
    usersFormError: document.getElementById('usersFormError'),
    newUserUsername: document.getElementById('newUserUsername'),
    newUserPassword: document.getElementById('newUserPassword'),
    newUserRole: document.getElementById('newUserRole'),
    libraryList: document.getElementById('libraryList'),
    libraryListHead: document.querySelector('.library-list-head'),
    libraryDetail: document.getElementById('libraryDetail'),
    libraryDetailBack: document.getElementById('libraryDetailBack'),
    libraryDetailTitle: document.getElementById('libraryDetailTitle'),
    libraryDetailMeta: document.getElementById('libraryDetailMeta'),
    libraryDetailBlurb: document.getElementById('libraryDetailBlurb'),
    libraryDetailContinue: document.getElementById('libraryDetailContinue'),
    libraryDetailNew: document.getElementById('libraryDetailNew'),
    libraryDetailDelete: document.getElementById('libraryDetailDelete'),
    libraryDetailTimeline: document.getElementById('libraryDetailTimeline'),
    catalogSearch: document.getElementById('catalogSearch'),
    catalogStatusFilter: document.getElementById('catalogStatusFilter'),
    pilotStatusBanner: document.getElementById('pilotStatusBanner'),
    homeEmpty: document.getElementById('homeEmpty'),
    completeEvalBtn: document.getElementById('completeEvalBtn'),
    workFooter: document.getElementById('workFooter'),
    completeDialog: document.getElementById('completeDialog'),
    completeDialogBackdrop: document.getElementById('completeDialogBackdrop'),
    completeDialogCancel: document.getElementById('completeDialogCancel'),
    completeDialogConfirm: document.getElementById('completeDialogConfirm'),
    completeDialogError: document.getElementById('completeDialogError'),
    completeNote: document.getElementById('completeNote'),
    signDialog: document.getElementById('signDialog'),
    signDialogBackdrop: document.getElementById('signDialogBackdrop'),
    signDialogSkip: document.getElementById('signDialogSkip'),
    signDialogConfirm: document.getElementById('signDialogConfirm'),
    signDialogError: document.getElementById('signDialogError'),
    downloadSignedBtn: document.getElementById('downloadSignedBtn'),
    newEvalBtn: document.getElementById('newEvalBtn'),
    newEvalPanel: document.getElementById('newEvalPanel'),
    cancelNewEvalBtn: document.getElementById('cancelNewEvalBtn'),
    startOpensslBtn: document.getElementById('startOpensslBtn'),
    refreshHomeBtn: document.getElementById('refreshHomeBtn'),
    workRemaining: document.getElementById('workRemaining'),
    workMustOpen: document.getElementById('workMustOpen'),
    workLowConf: document.getElementById('workLowConf'),
    pdfReadiness: document.getElementById('pdfReadiness'),
    pdfReadinessTitle: document.getElementById('pdfReadinessTitle'),
    pdfReadinessStatus: document.getElementById('pdfReadinessStatus'),
    pdfMissingList: document.getElementById('pdfMissingList'),
    appToast: document.getElementById('appToast'),
    saveStatus: document.getElementById('saveStatus'),
    saveStatusSep: document.getElementById('saveStatusSep'),
    authGate: document.getElementById('authGate'),
    authForm: document.getElementById('authForm'),
    accessCodeInput: document.getElementById('accessCodeInput'),
    authEnterBtn: document.getElementById('authEnterBtn'),
    authBrowseBtn: document.getElementById('authBrowseBtn'),
    authGateError: document.getElementById('authGateError'),
    authHeaderBtn: document.getElementById('authHeaderBtn'),
    authHint: document.getElementById('authHint'),
    moreMenuBtn: document.getElementById('moreMenuBtn'),
    moreMenuPanel: document.getElementById('moreMenuPanel'),
    toggleTechBtn: document.getElementById('toggleTechBtn'),
    toggleTechDetailsBtn: document.getElementById('toggleTechDetailsBtn'),
    techPanel: document.getElementById('techPanel'),
    techDetailsPanel: document.getElementById('techDetailsPanel'),
    techDetails: document.getElementById('techDetails'),
    collectionBanner: document.getElementById('collectionBanner'),
    collectionBannerTitle: document.getElementById('collectionBannerTitle'),
    collectionBannerProgress: document.getElementById('collectionBannerProgress'),
    collectionBannerDetail: document.getElementById('collectionBannerDetail'),
    collectionLogBtn: document.getElementById('collectionLogBtn'),
    collectionRetryBtn: document.getElementById('collectionRetryBtn'),
    evidencePack: document.getElementById('evidencePack'),
    evidencePackLinks: document.getElementById('evidencePackLinks'),
    metaIdentity: document.getElementById('metaIdentity'),
    metaLibraryType: document.getElementById('metaLibraryType'),
    metaAssessmentDate: document.getElementById('metaAssessmentDate'),
    ratingDiffBanner: document.getElementById('ratingDiffBanner'),
    ratingDiffDetail: document.getElementById('ratingDiffDetail'),
    ratingDiffList: document.getElementById('ratingDiffList'),
    backHomeBtn: document.getElementById('backHomeBtn'),
    pipelineDrawer: document.getElementById('pipelineDrawer'),
    pipelineBackdrop: document.getElementById('pipelineBackdrop'),
    pipelineCloseBtn: document.getElementById('pipelineCloseBtn'),
    pipelineFab: document.getElementById('pipelineFab'),
    repoInput: document.getElementById('repo'),
    repoMeta: document.getElementById('repoMeta'),
    tokenRow: document.getElementById('tokenRow'),
    tokenInput: document.getElementById('token'),
    runBtn: document.getElementById('runBtn'),
    status: document.getElementById('status'),
    pipelineCard: document.getElementById('pipelineCard'),
    pipelineTitle: document.getElementById('pipelineTitle'),
    pipelinePhase: document.getElementById('pipelinePhase'),
    pipelineAlive: document.getElementById('pipelineAlive'),
    pipelineProgressFill: document.getElementById('pipelineProgressFill'),
    log: document.getElementById('log'),
    json: document.getElementById('json'),
    summary: document.getElementById('summary'),
    summaryHint: document.getElementById('summaryHint'),
    exampleSelect: document.getElementById('exampleSelect'),
    loadExampleBtn: document.getElementById('loadExampleBtn'),
    formFileInput: document.getElementById('formFileInput'),
    loadFileBtn: document.getElementById('loadFileBtn'),
    fileStatus: document.getElementById('fileStatus'),
    details: document.getElementById('details'),
    expandAllBtn: document.getElementById('expandAllBtn'),
    collapseAllBtn: document.getElementById('collapseAllBtn'),
    recalcBtn: document.getElementById('recalcBtn'),
    downloadBtn: document.getElementById('downloadBtn'),
    downloadPdfBtn: document.getElementById('downloadPdfBtn'),
    downloadPdfDraftBtn: document.getElementById('downloadPdfDraftBtn'),
    saveDraftBtn: document.getElementById('saveDraftBtn'),
    restoreDraftBtn: document.getElementById('restoreDraftBtn'),
    draftSelect: document.getElementById('draftSelect'),
    refreshDraftsBtn: document.getElementById('refreshDraftsBtn'),
    loadDraftBtn: document.getElementById('loadDraftBtn'),
};

export const state = {
    eventSource: null,
    form: null,
    draftId: null,
    tokenRequired: false,
    tokenRowForced: false,
    auth: {
        enabled: false,
        authenticated: true,
        openMode: true,
        role: null,
        userId: null,
        username: null,
        canManageUsers: false,
        canWrite: true,
        userAuthEnabled: false,
        pilotCodeEnabled: false,
        browseWithoutCode: false,
    },
    view: 'home',
    exampleFiles: [],
    drafts: [],
    libraries: [],
    catalogQ: '',
    catalogStatus: 'all',
    selectedLibraryId: null,
    selectedLibraryDetail: null,
    ai: {
        enabled: false,
        available: false,
        provider: null,
    },
    pendingSignEvaluationId: null,
    pipeline: {
        status: 'idle',
        activeStep: null,
        doneSteps: new Set(),
        failedStep: null,
        failedSteps: new Set(),
        startedAt: 0,
        lastLogAt: 0,
        aliveTimer: null,
        phaseMessage: 'Čeká na spuštění.',
        evaluationId: null,
        repoInput: '',
        humanStatus: 'idle',
    },
};

export const EXAMPLE_CATALOG = {};

export const LOCAL_DRAFT_KEY = 'nukib-oss-reviewer-draft-v1';
export const LAST_OPEN_KEY = 'nukib-oss-reviewer-last-open-v1';
export const AUTOSAVE_LOCAL_MS = 250;
export const AUTOSAVE_SERVER_MS = 900;
export const timers = {
    localDraft: null,
    serverDraft: null,
    serverSaveGeneration: 0,
    lastSaveStatus: { kind: '', at: '' },
};

export const PIPELINE_STEPS = ['1', '2', '3', '4', '5', 'finalize'];
export const PIPELINE_STEP_LABELS = {
    '1': 'Krok 1: Předpoklady',
    '2': 'Krok 2: OSS vývoj',
    '3': 'Krok 3: Kód a CI',
    '4': 'Krok 4: Dokumentace',
    '5': 'Krok 5: Crypto API',
    finalize: 'Finalizace',
};

