"""Compatibility facade — prefer `db.repos` for new code."""
from __future__ import annotations

from db.repos import *  # noqa: F403
from db.repos import (
    ARTIFACTS_DIR,
    ROOT,
    add_audit,
    add_event,
    authenticate_user,
    build_evaluation_title,
    can_edit_evaluation,
    complete_evaluation,
    create_user,
    delete_evaluation,
    delete_library,
    delete_user,
    ensure_bootstrap_admin,
    ensure_pilot_user,
    evaluation_to_list_item,
    extract_form_identity,
    get_evaluation,
    get_library_detail,
    get_or_create_library,
    get_or_create_library_version,
    get_user_by_username,
    list_evaluations,
    list_libraries,
    list_pilot_empirie,
    list_users,
    migrate_file_drafts,
    rating_diff_against_previous,
    save_evaluation,
    seed_pilot_evaluations,
    seed_pilot_libraries,
    sign_evaluation,
    status_label_cs,
    update_user,
    upsert_form_artifact,
    user_to_dict,
)

# Private helpers still referenced by older tests / code
from db.repos.common import _library_name, _parse_iso, _safe_id  # noqa: F401

__all__ = [
    "ARTIFACTS_DIR",
    "ROOT",
    "add_audit",
    "add_event",
    "authenticate_user",
    "build_evaluation_title",
    "can_edit_evaluation",
    "complete_evaluation",
    "create_user",
    "delete_evaluation",
    "delete_library",
    "delete_user",
    "ensure_bootstrap_admin",
    "ensure_pilot_user",
    "evaluation_to_list_item",
    "extract_form_identity",
    "get_evaluation",
    "get_library_detail",
    "get_or_create_library",
    "get_or_create_library_version",
    "get_user_by_username",
    "list_evaluations",
    "list_libraries",
    "list_pilot_empirie",
    "list_users",
    "migrate_file_drafts",
    "rating_diff_against_previous",
    "save_evaluation",
    "seed_pilot_evaluations",
    "seed_pilot_libraries",
    "sign_evaluation",
    "status_label_cs",
    "update_user",
    "upsert_form_artifact",
    "user_to_dict",
]
