"""Persistence repositories split by domain."""

from db.repos.audit import add_audit, ensure_pilot_user
from db.repos.common import ARTIFACTS_DIR, ROOT, library_name, parse_iso, safe_id
from db.repos.evaluations import (
    add_event,
    build_evaluation_title,
    can_edit_evaluation,
    complete_evaluation,
    delete_evaluation,
    extract_form_identity,
    get_evaluation,
    list_evaluations,
    list_pilot_empirie,
    migrate_file_drafts,
    rating_diff_against_previous,
    save_evaluation,
    sign_evaluation,
    upsert_form_artifact,
)
from db.repos.libraries import (
    delete_library,
    get_library_detail,
    get_or_create_library,
    get_or_create_library_version,
    list_libraries,
)
from db.repos.presenters import evaluation_to_list_item, status_label_cs
from db.repos.seed import seed_pilot_evaluations, seed_pilot_libraries
from db.repos.users import (
    authenticate_user,
    create_user,
    delete_user,
    ensure_bootstrap_admin,
    get_user_by_username,
    list_users,
    update_user,
    user_to_dict,
)

__all__ = [
    "ARTIFACTS_DIR",
    "ROOT",
    "add_audit",
    "add_event",
    "authenticate_user",
    "build_evaluation_title",
    "can_edit_evaluation",
    "complete_evaluation",
    "create_user",
    "delete_evaluation",
    "delete_library",
    "delete_user",
    "ensure_bootstrap_admin",
    "ensure_pilot_user",
    "evaluation_to_list_item",
    "extract_form_identity",
    "get_evaluation",
    "get_library_detail",
    "get_or_create_library",
    "get_or_create_library_version",
    "get_user_by_username",
    "library_name",
    "list_evaluations",
    "list_libraries",
    "list_pilot_empirie",
    "list_users",
    "migrate_file_drafts",
    "parse_iso",
    "rating_diff_against_previous",
    "safe_id",
    "save_evaluation",
    "seed_pilot_evaluations",
    "seed_pilot_libraries",
    "sign_evaluation",
    "status_label_cs",
    "update_user",
    "upsert_form_artifact",
    "user_to_dict",
]
